services:
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
    db:
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: refactorian
            MYSQL_USER: refactorian
            MYSQL_PASSWORD: refactorian
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
    adminer:
        image: adminer
        ports:
            - 9090:8080
        depends_on:
        - db
    mail:
        image: axllent/mailpit:latest
        ports:
        - 8025:8025
        - 1025:1025
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379
